/** Logo and artwork paths, extracted from the prototype's inline base64 payload. */
export const ASSETS: Record<string, string> = {
  "Asana": "/assets/asana.svg",
  "Backlog": "/assets/backlog.webp",
  "ChatGPT": "/assets/chatgpt.svg",
  "Chatwork": "/assets/chatwork.webp",
  "Claude": "/assets/claude.svg",
  "Cursor": "/assets/cursor.svg",
  "Garoon": "/assets/garoon.webp",
  "Gmail": "/assets/gmail.webp",
  "Google Calendar": "/assets/google-calendar.webp",
  "Google Drive": "/assets/google-drive.webp",
  "Google Meet": "/assets/google-meet.svg",
  "Google カレンダー": "/assets/google-calendar.webp",
  "HubSpot": "/assets/hubspot.webp",
  "kintone": "/assets/kintone.webp",
  "LINE WORKS": "/assets/line-works.webp",
  "Linear": "/assets/linear.svg",
  "Meet": "/assets/google-meet.svg",
  "Microsoft Teams": "/assets/microsoft-teams.webp",
  "Notion": "/assets/notion.webp",
  "Outlook": "/assets/outlook.webp",
  "pulse-blue-art": "/assets/pulse-blue-art.png",
  "pulse-presentation-faces": "/assets/pulse-presentation-faces.png",
  "Salesforce": "/assets/salesforce.webp",
  "Sansan": "/assets/sansan.webp",
  "Slack": "/assets/slack.webp",
  "Teams": "/assets/microsoft-teams.webp",
  "UNCHAIN": "/assets/unchain.webp",
  "zoom": "/assets/zoom.webp",
  "Zoom": "/assets/zoom.webp",
};
