'use client';
import {useTranslations} from 'next-intl';
import {useState,type FormEvent} from 'react';
import s from './ContactForm.module.css';
const WEB3FORMS_ACCESS_KEY=process.env.NEXT_PUBLIC_WEB3FORMS_ACCESS_KEY??'5b436ee0-6aed-44f7-8347-6180b1aac674';
const fields=['name','company','email','personal','role','topic','teamSize','meetings','message'];
type Status='idle'|'sending'|'sent'|'error';
export function ContactForm(){const t=useTranslations('site.contact');const [status,setStatus]=useState<Status>('idle');
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(status==='sending')return;const form=e.currentTarget;const data=new FormData(form);
const payload:Record<string,string>={access_key:WEB3FORMS_ACCESS_KEY,subject:'Pulse — '+t('title'),from_name:'Pulse Website',botcheck:String(data.get('botcheck')??'')};
for(const k of fields){const v=data.get(k);if(v)payload[t(k)]=String(v);}
const email=data.get('email');if(email)payload.replyto=String(email);
setStatus('sending');
try{const res=await fetch('https://api.web3forms.com/submit',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(payload)});const json=await res.json();if(!res.ok||!json.success)throw new Error(json.message||'Submit failed');form.reset();setStatus('sent');}
catch{setStatus('error');}}
return <section className={`${s.page} wrap`}><div className={s.copy}><small>PULSE / CONTACT</small><h1>{t('title')}</h1><p>{t('intro')}</p><ul>{['benefitOne','benefitTwo','benefitThree'].map((key,i)=><li key={key}><span>0{i+1}</span>{t(key)}</li>)}</ul><h2>{t('process')}</h2><p>{t('processBody')}</p><a href="mailto:contact@the-unchain.com">contact@the-unchain.com ↗</a></div><form className={s.form} onSubmit={submit}><h2>{t('formTitle')}</h2><input type="checkbox" name="botcheck" className={s.honeypot} tabIndex={-1} autoComplete="off" aria-hidden="true"/><div className={s.grid}>{['name','company','email','personal','role'].map(k=><label key={k}>{t(k)}<input name={k} type={k==='email'||k==='personal'?'email':'text'} required={!['personal','role'].includes(k)} autoComplete={k==='company'?'organization':k==='personal'?'email':k==='role'?'organization-title':k}/></label>)}<label>{t('topic')}<select name="topic" defaultValue=""><option value="" disabled>{t('select')}</option>{['topicTrial','topicRollout','topicOther'].map(k=><option key={k}>{t(k)}</option>)}</select></label>{[['teamSize',['1','2–5','6–20','21–100','101+']],['meetings',['0–4','5–10','11–20','21+']]].map(([key,options])=><label key={key as string}>{t(key as string)}<select name={key as string} required defaultValue=""><option value="" disabled>{t('select')}</option>{(options as string[]).map(v=><option key={v}>{v}</option>)}</select></label>)}</div><label>{t('message')}<textarea name="message" rows={5} required defaultValue={t('initial')} onInput={e=>{e.currentTarget.style.height='auto';e.currentTarget.style.height=e.currentTarget.scrollHeight+'px'}}/></label><button type="submit" className="btn btn-dark" disabled={status==='sending'}>{status==='sending'?t('sending'):t('send')+' →'}</button>{status==='sent'?<p className={s.ok} role="status">{t('sent')}</p>:status==='error'?<p className={s.err} role="alert">{t('error')}</p>:<p>{t('note')}</p>}</form></section>}
