'use client';
import {useState} from 'react';
import {useTranslations} from 'next-intl';
import {PulseMark} from '../PulseMark';
import type {Sector} from './UseCaseVisual';
import p from './ProductPanels.module.css';
const icons:Record<string,string>={Salesforce:'salesforce.webp',HubSpot:'hubspot.webp',Linear:'linear.svg',Asana:'asana.svg',kintone:'kintone.webp',Notion:'notion.webp'};
export function ProductPanels({sector,kind}:{sector:Sector;kind:'email'|'sync'|'example'|'brief'}){
 const t=useTranslations(`site.useCases.${sector}`),c=useTranslations('site.useCases.common');
 const [done,setDone]=useState(false);
 const chrome=<header className={p.chrome}><span className={p.brand}><PulseMark/>Pulse</span><span>{c('workspace')}</span><span className={p.dots}>•••</span></header>;
 if(kind==='brief')return <div className={`${p.frame} ${p.briefFrame}`}><div className={p.product}>{chrome}<div className={p.content}><div className={p.breadcrumb}>{c('yourBrief')} <span>09:45</span></div><h3>{t('meeting')}</h3><div className={p.meta}>{c('today')} · {c('private')}</div><p className={p.lead}>{t('briefText')}</p><div className={p.person}><span>{t('personInitial')}</span><div><b>{t('person')}</b><small>{t('personRole')}</small></div></div><h4>{c('previous')}</h4><p>{t('decision')}</p><h4>{c('open')}</h4><p>{t('question')}</p><div className={p.evidence}>▤ {c('sources')} <span>09/18 · 09/22</span></div></div></div></div>;
 if(kind==='example')return <div className={`${p.frame} ${p.contextFrame}`}><div className={p.product}>{chrome}<div className={p.content}><div className={p.breadcrumb}>{c('contextRecord')} <span>CTX–0925</span></div><h3>{t('meeting')}</h3><div className={p.meta}><span className={p.status}>✓ {c('linked')}</span> {c('today')}</div><div className={p.quote}><small>{c('exampleBefore')} · 18:42</small><p>“{t('rough').split('\n')[0]}”</p></div><dl className={p.fields}><div><dt>{c('decided')}</dt><dd>{t('decision')}</dd></div><div><dt>{c('owner')}</dt><dd>{t('person')}</dd></div><div><dt>{c('next')}</dt><dd>{t('action')}</dd></div><div><dt>{c('statusLabel')}</dt><dd><span className={p.pending}>{c('pending')}</span></dd></div></dl><div className={p.evidence}>▤ {c('sources')} <span>09/25 · 18:42</span></div></div></div></div>;
 const sync=kind==='sync';
 return <div className={`${p.frame} ${sync?p.syncFrame:p.emailFrame}`}><div className={p.product}>{chrome}<div className={p.toolbar}><img src={'/assets/'+(sync?icons[t('tool')]:'gmail.webp')} alt={sync?t('tool'):'Gmail'}/><div><b>{sync?t('tool'):c('draft')}</b><small>{sync?c('ready'):c('draftSaved')}</small></div><span className={p.status}>{done?'✓':c('review')}</span></div><div className={p.content}>{sync?<><div className={p.breadcrumb}>{t('meeting')} <span>09/25</span></div><dl className={p.fields}><div><dt>{t('field')}</dt><dd><small className={p.previous}>{c('notUpdated')}</small><strong>{t('value')}</strong></dd></div><div><dt>{c('owner')}</dt><dd>{t('person')}</dd></div><div><dt>{c('next')}</dt><dd>{t('action')}</dd></div><div><dt>{c('sources')}</dt><dd className={p.sourceText}>▤ {t('meeting')} · 18:42</dd></div></dl><div className={p.reviewNote}>✓ {c('reviewNote')}</div></>:<><div className={p.mailField}><span>{c('to')}</span><b>{t('mailTo')}</b></div><div className={p.mailField}><span>{c('subject')}</span><b>{t('mailSubject')}</b></div><div className={p.mailBody}><p>{t('mailGreeting')}</p><p>{t('mail')}</p><ul><li>{t('action')}</li><li>{t('question')}</li></ul><p>{c('mailClose')}<br/>Pulse</p></div><div className={p.attachment}>▤ {t('attachment')} <small>PDF · 248 KB</small></div></>}</div><footer className={p.actions}><button disabled={done} onClick={()=>setDone(true)}>{c(done?(sync?'applied':'sent'):(sync?'apply':'send'))} {done?'✓':'↗'}</button><small>{c('preview')}</small></footer></div></div>;
}
