'use client';
import {ProductPanels} from './ProductPanels';
import {PulseMark} from '../PulseMark';
import {useState} from 'react';
import {useTranslations} from 'next-intl';
import s from './UseCase.module.css';
export type Sector='sales'|'customer-success'|'product'|'marketing'|'operations'|'hr';
const assets:Record<string,string>={Salesforce:'salesforce.webp',HubSpot:'hubspot.webp',Linear:'linear.svg',Asana:'asana.svg',kintone:'kintone.webp',Notion:'notion.webp'};
export function AppLogo({name,file}:{name:string;file?:string}){return <img src={`/assets/${file||assets[name]}`} alt={name} width={36} height={36}/>}
export function UseCaseVisual({sector,kind}:{sector:Sector;kind:'hero'|'brief'|'bot'|'notes'|'email'|'sync'|'search'|'example'|'platforms'|'tools'}){
 const t=useTranslations(`site.useCases.${sector}`),c=useTranslations('site.useCases.common');
 const [organized,setOrganized]=useState(false),[answer,setAnswer]=useState(false);
 if(kind==='brief'||kind==='email'||kind==='sync'||kind==='example')return <ProductPanels sector={sector} kind={kind}/>;
 const chrome=<div className={s.windowBar}><span aria-hidden="true"><i/><i/><i/></span><b className="pulse-brand-inline"><PulseMark/>Pulse</b><small>{c('private')}</small></div>;
 const note=<><h3>{t('meeting')}</h3><small className={s.metadata}>{c('today')}</small><h4>{c('decided')}</h4><p>{t('decision')}</p><h4>{c('next')}</h4><p>{t('action')}</p><span className={s.source}>↗ {c('sources')} · 18:42</span></>;
 if(kind==='hero')return <div className={`${s.canvas} ${s.heroVisual}`}><div className={s.art}/><div className={s.heroNote}>{chrome}<div className={s.noteContent}>{note}</div></div><div className={s.callTile}><div className={s.callPortrait} role="img" aria-label={c('peopleOnly')}/><div><PulseMark/>{c('recordingLabel')}</div></div><div className={s.heroTag}>✧ {c('next')}<strong>{t('action')}</strong></div></div>;
 if(kind==='bot')return <div className={`${s.canvas} ${s.botVisual}`}><img src="/assets/pulse-editorial-portraits.png" alt={c('peopleOnly')}/><div className={s.botRequests}>{[0,1,2].map(i=><div key={i}><span>▤</span><b>{c('botFree')}</b><strong>×</strong></div>)}</div></div>;
 if(kind==='notes')return <div className={`${s.canvas} ${s.notesVisual}`}><div className={s.noteWindow}>{chrome}<div className={s.noteContent}><h3>{t('meeting')}</h3><div className={s.viewTabs}><button aria-pressed={!organized} onClick={()=>setOrganized(false)}>{c('notes')}</button><button aria-pressed={organized} onClick={()=>setOrganized(true)}>✧ {c('organized')}</button></div><div className={s.noteArea}>{organized?<><h4>{c('decided')}</h4><p>{t('decision')}</p><h4>{c('next')}</h4><p>{t('action')}</p><span className={s.source}>↗ {c('sources')} · 18:42</span></>:<><p className={s.rough}>{t('rough')}</p><button className={s.smallButton} onClick={()=>setOrganized(true)}>✧ {c('organized')} →</button></>}</div></div></div></div>;
 if(kind==='search')return <div className={`${s.canvas} ${s.searchVisual}`}><div className={s.searchWindow}><aside><b className="pulse-brand-inline"><PulseMark/>Pulse</b><span>{c('evidence')}</span>{[0,1,2].map((n)=><div key={n}><small>0{n+1} / 09.{18+n*3}</small><strong>{t('meeting')}</strong></div>)}</aside><div className={s.chat}><div className={s.chatHead}>✧ {c('question')}</div><div className={s.questionBubble}>{t('query')}</div>{answer?<div className={s.answer} aria-live="polite"><small>{c('answer')}</small><p>{t('answerText')}</p><span className={s.source}>{t('meeting')} ↗</span></div>:<button className={s.askButton} onClick={()=>setAnswer(true)}>{c('ask')} →</button>}<div className={s.chatPrompt}>{t('query')}<span aria-hidden="true">↑</span></div></div></div></div>;
 if(kind==='platforms')return <div className={`${s.canvas} ${s.platformVisual}`}><div className={s.platformLogos}>{[['Zoom','zoom.svg'],['Google Meet','google-meet.svg'],['Teams','microsoft-teams.svg']].map(([name,file])=><span key={name}><AppLogo name={name} file={file}/><small>{name}</small></span>)}</div><img className={s.roomImage} src="/assets/pulse-editorial-room.png" alt={c('peopleOnly')}/><div className={s.platformCaption}>Pulse / {c('capturing')}</div></div>;
 return <div className={`${s.canvas} ${s.toolsVisual}`}><div className={s.toolLogos}>{[['Calendar','google-calendar.webp'],[t('tool'),assets[t('tool')]],['Slack','slack.webp'],['Drive','google-drive.webp']].map(([name,file])=><span key={name}><AppLogo name={name} file={file}/></span>)}</div><div className={s.connectionLines} aria-hidden="true">↓</div><div className={s.calendarCard}><small>Pulse · {c('prepared')}</small><h3>{t('meeting')}</h3><p>{t('question')}</p><span className={s.source}>{c('today')}</span></div></div>;
}
