import {PulseMark} from '../PulseMark';
import Link from 'next/link';
import {useTranslations,useLocale} from 'next-intl';
import s from './Handoff.module.css';

/* The diagram reads top to bottom: the AI clients, the MCP exchange, the Pulse
   layer, then the sources. The dotted fans are drawn as one SVG each so the
   lines always meet the centre of the row below them — the old CSS rails drifted
   out of alignment as the column resized. */
const DASH = {strokeDasharray: '3 4', vectorEffect: 'non-scaling-stroke'} as const;

export function PulseAiHandoff(){const t=useTranslations('site.home.pulseAiHandoff'),locale=useLocale();return <section className={s.section} id="mcp"><div className="wrap"><div className={s.copy}><span className="eyebrow">{t('pulseMcp')}</span><h2>{t.rich('connectContextAiThrough',{br:()=> <br/>})}</h2><p>{t('makeConnectedMeetingsDocuments')}</p><p className={s.emphasis}>{t('diagramFoot')}</p><Link className="text-link" href={`/${locale}/integrations#technology`}>{t('exploreIntegrationsTechnology')}</Link></div><div className={s.diagram}><span className={s.label}>{t('diagramAi')}</span><div className={s.aiRow}>{[['Claude','claude.svg'],['ChatGPT','chatgpt.svg'],['Cursor','cursor.svg']].map(([name,icon])=><div key={name}><img src={'/assets/'+icon} alt=""/><span>{name}</span></div>)}</div><svg className={s.fan} viewBox="0 0 100 60" preserveAspectRatio="none" aria-hidden="true">{[15.333,50,84.667].map(x=><path key={x} d={`M${x} 0 L50 60`} fill="none" stroke="currentColor" strokeWidth="1" {...DASH}/>)}</svg><div className={s.exchange}><span>↓ {t('diagramRequest')}</span><b>MCP</b><span>↑ {t('diagramResponse')}</span></div><div className={s.layer}><span className={s.pulse}><PulseMark/>Pulse</span><h3>{t('diagramLayer')}</h3><div>{['diagramMeaning','diagramRelations','diagramSources'].map(key=><span key={key}>{t(key)}</span>)}</div></div><div className={s.inputArrow} aria-hidden="true">↑</div><svg className={s.fan} viewBox="0 0 100 60" preserveAspectRatio="none" aria-hidden="true">{[21.2,35.6,50,64.4,78.8].map(x=><path key={x} d={`M50 0 L${x} 60`} fill="none" stroke="currentColor" strokeWidth="1" {...DASH}/>)}</svg><div className={s.data}><div className={s.dataIcons}>{[['Slack','slack.webp'],['Gmail','gmail.webp'],['Notion','notion.webp'],['Drive','google-drive.webp'],['Salesforce','salesforce.webp']].map(([name,icon])=><span key={name} className={s.dataTile}><img src={'/assets/'+icon} alt={name}/></span>)}</div><span>{t('diagramData')}</span></div></div></div></section>}
