"use client";
import {useEffect,useRef,useState} from 'react';
import {useTranslations} from 'next-intl';
import s from './Capabilities.module.css';
const features=['captureWithoutMeetingBot','useUsualMeetingApp','privateFirstShareChoice','notesPersonConversationsUse','connectedCalendarFindUpcoming'] as const;
const apps=[['Zoom','zoom.webp'],['Google Meet','google-meet.svg'],['Microsoft Teams','microsoft-teams.webp']];
const tools=[['Slack','slack.webp'],['Gmail','gmail.webp'],['Salesforce','salesforce.webp'],['Notion','notion.webp'],['Google Drive','google-drive.webp'],['kintone','kintone.webp']];
function PulseMark(){return <span className={s.pulseMark}><svg viewBox="0 0 40 40" aria-hidden="true"><path d="M7 21h7l4-10 5 20 4-10h7" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"/></svg>Pulse</span>}
export function V7Capabilities(){
 const t=useTranslations('site.home.v7Capabilities'),v=useTranslations('site.home.scenes');
 const root=useRef<HTMLElement>(null),[selected,setSelected]=useState(0),[speaker,setSpeaker]=useState(0);
 useEffect(()=>{let frame=0;const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const el=root.current;if(!el)return;const distance=el.offsetHeight-window.innerHeight;const progress=Math.max(0,Math.min(.999,(-el.getBoundingClientRect().top+80)/distance));setSelected(Math.min(4,Math.floor(progress*5)));});};update();window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',update);window.removeEventListener('resize',update);};},[]);
 const go=(i:number)=>{const el=root.current;if(!el)return;const distance=el.offsetHeight-window.innerHeight;window.scrollTo({top:window.scrollY+el.getBoundingClientRect().top-80+(i+.12)*distance/5,behavior:'instant'});setSelected(i);};
 const names=['bot','app','private','room','tools'];
 return <section ref={root} className={s.section} id="everyday-work"><div className={s.sticky}><div className="wrap">
 <header className={s.heading}><div><span>{t('builtAroundWork')}</span><h2>{t.rich('whereverMeetHoweverWork',{br:()=> <br/>})}</h2></div><small>{v('scroll')} <span aria-hidden="true">↓</span></small></header>
 <div className={s.layout}><div className={s.features}>{features.map((key,i)=><button key={key} aria-label={v(`${names[i]}Title`)} aria-pressed={selected===i} aria-controls="capability-preview" onClick={()=>go(i)}><small>0{i+1}</small><span>{t.rich(key,{strong:c=><strong>{c}</strong>,span:c=><span>{c}</span>})}</span></button>)}</div>
 <div className={s.stage} id="capability-preview" role="region" aria-label={v(`${names[selected]}Title`)}><div className={s.sceneHead}><span>0{selected+1} / 05</span><h3>{v(`${names[selected]}Title`)}</h3><p>{v(`${names[selected]}Note`)}</p></div>
 {selected===0&&<div className={s.botScene}><img className={s.sceneImage} src="/assets/pulse-no-bots.png" alt={v("botTitle")}/><div className={s.recordBadge}><PulseMark/><span>{v('local')}</span><strong>✓ {v('noBot')}</strong></div></div>}
 {selected===1&&<div className={s.appScene}><div className={s.appRow}>{apps.map(([name,icon])=><div key={name}><img src={'/assets/'+icon} alt=""/><strong>{name}</strong></div>)}</div><img className={s.sceneImage} src="/assets/pulse-team-work.png" alt={v("appTitle")}/></div>}
 {selected===2&&<div className={s.sharingScene}><div className={s.privateBox}><span className={s.lock} aria-hidden="true"><svg width="26" height="30" viewBox="0 0 26 30" aria-hidden="true"><rect x="4" y="12" width="18" height="15" rx="3" fill="none" stroke="currentColor" strokeWidth="1.5"/><path d="M8 12V8a5 5 0 0110 0v4m-5 6v4" fill="none" stroke="currentColor" strokeWidth="1.5"/></svg></span><h4>{v('private')}</h4><p>{v('privateSub')}</p><div className={s.paperStack} aria-hidden="true"><i/><i/><i/></div></div><span className={s.arrow} aria-hidden="true">↓</span><div className={s.contextBox}><PulseMark/><h4>{v('choose')}</h4><p>{v('chooseSub')}</p></div><div className={s.shareBranches} aria-hidden="true"><span>↙</span><span>↘</span></div><div className={s.recipients}><div><span>A B</span><strong>{v('team')}</strong></div><div><span>C D</span><strong>{v('external')}</strong></div></div><p className={s.shareFoot}>{v('shareFoot')}</p></div>}
 {selected===3&&<div className={s.roomScene}><div className={s.roomArt}><img className={s.sceneImage} src="/assets/pulse-meeting-room.png" alt={v('roomTitle')}/><span className={s.roomPulse}>Pulse</span><div className={s.speakerButtons}>{['A','B','C','D'].map((name,i)=><button key={name} aria-pressed={speaker===i} onClick={()=>setSpeaker(i)} aria-label={`${v('person')} ${name}`}>{name}</button>)}</div></div><div className={s.speakerNote} aria-live="polite"><b>{['A','B','C','D'][speaker]}</b><p>{v(`quote${['A','B','C','D'][speaker]}`)}</p><small>12:{40+speaker*4}</small></div></div>}
 {selected===4&&<div className={s.toolsScene}><div className={s.toolGrid}>{tools.map(([name,icon])=><div key={name}><img src={'/assets/'+icon} alt=""/><span>{name}</span></div>)}</div><div className={s.funnel} aria-hidden="true">↓　↓　↓</div><div className={s.contextBox}><PulseMark/><h4>{v('context')}</h4></div><p className={s.toolsFoot}>{v('toolsFoot')}</p></div>}
 <p className={s.caption}>{v('sample')}</p></div></div></div></div></section>;
}
